name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kamiazya
          template: classic
          base: activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: A
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_identicons: yes
          plugin_people_types: stargazers, contributors, watchers, followers, following
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: stars
